### ISSUE TITLE
touchpad not working

### ISSUE THREAD

**Issue by logic10492** [jimlee2048/Hackintosh-Lenovo-Legion-R7000P2020H#3]
after I installed Sonoma 14.3
the touchpad is not working
I am new of using hackintosh,if some log from my device can help I will

**Comment by jimlee2048** [comment]
What's your model? Legion R7000P2020H?

Maybe your touchpad not made by Synaptic, thus not compatible with current touchpad driver [VoodooRMI](https://github.com/VoodooSMBus/VoodooRMI). You can try standard I2C touchpad driver instead. To do this, edit your opencore `config.plist`, disable the red marked kexts, then enable the blue marked kexts.

![image](https://github.com/jimlee2048/Hackintosh-Lenovo-Legion-R7000P2020H/assets/21117946/c1271daa-7666-49f3-9480-f090e8fd434f)

**Comment by logic10492** [comment]
oh after I did what you say my touchpad is just working
thank for your help and I
