### ISSUE TITLE
BIOS无法修改显存

### ISSUE THREAD

**Issue by annkqb** [jimlee2048/Hackintosh-Lenovo-Legion-R7000P2020H#4]
您好，我是一名黑苹果小白。在黑苹果的操作中遇到了两点问题 请问能否提供帮助
1是我根据[W2725730722](https://github.com/W2725730722/Lenovo-R7000P-2020-Hackintosh)的教程设置bios 但每次重启后bios中的 Security > Secure Boot 及AMD CBS > NBIO Common Options > GFX Configuration（https://github.com/wushuo894/Lenovo-R7000P-2020-Hackintosh/blob/main/images/Xnip2023-06-13_21-12-14.jpg）会自动回退到默认状态 请问如何进行锁定 或者是用配置文件进行锁定 
2是原来我是根据[W2725730722](https://github.com/W2725730722/Lenovo-R7000P-2020-Hackintosh)设置的ventura 现在需要升级您的sonoma 我将黑苹果的efi分区删除后替换为您的efi 在选择页面刷了段代码后就又会重启无法引导 请问如何解决 感谢

**Comment by jimlee2048** [comment]
问题1：推荐使用[UMAF](https://github.com/DavidS95/Smokeless_UMAF)设置显存大小，简要方法如下：

- 准备一个U盘，格式化为FAT32格式
- 下载并解压[UniversalAMDFormBrowser.zip](https://github.com/DavidS95/Smokeless_UMAF/blob/main/UniversalAMDFormBrowser.zip)里的所有文件，复制到U盘的根目录下
- 插入U盘，重启，选择U盘的启动项，进入UMAF界面
- Device Manager > AMD CBS > NBIO Common Options > GFX Configuration > UMA Frame Buffer Size【设为 2G】
- 保存并退出

注意：后续如果在BIOS进行更改（如修改启动项），会使先前在UMAF设置的显存大小失效，此时需要重新进UMAF改一遍。

另：推荐升级BIOS版本到最新的FSCN28WW，能解决各种奇怪睡眠问题。虽然新版BIOS无法启用魔改选项，但UMAF能够有效替代。

**Comment by jimlee2048** [comment]
~~问题2：每次升级/安装系统前，需要禁用显卡驱动`NootReded.kext`，升级/安装完成并成功进入一次桌面后，再重新启用，请检查。~~

由于使用了部分Sonoma专版驱动，本仓库的EFI只能在Sonoma上工作。为避免奇怪的问题，建议你使用本仓库的EFI全新安装Sonoma。

如果你想保留现有系统数据升级，你也可以：
- 先使用现有的Ventura EFI进入现有系统，进入系统设置触发升级Sonoma。
- 在准备升级重启前，替换EFI为我的Sonoma EFI。
- 替换EFI时，请务必禁用显卡驱动`NootReded.kext`，待升级完成并成功进入一次桌面后再重新启用。

注意：以上操作仅供参考，我没有尝试过，请注意备份数据，风险自负。

**Comment by annkqb** [comment]
确认了一下 很意外 是我的主板电池没电了造成的bios回退问题  请问ventura和sonoma的efi除了sonoma专用驱动外还有哪里是有差异的吗？如果是自己配置的旧版oc ventura efi想自己升级sonoma的efi应该如何进行操作 感谢! 另外在windows环境下您是通过什么渠道获取最新版macos dmg格式镜像的呢 感谢

**Comment by jimlee2048** [comment]
> 确认了一下 很意外 是我的主板电池没电了造成的bios回退问题 请问ventura和sonoma的efi除了sonoma专用驱动外还有哪里是有差异的吗？如果是自己配置的旧版oc ventura efi想自己升级sonoma的efi应该如何进行操作 感谢! 另外在windows环境下您是通过什么渠道获取最新版macos dmg格式镜像的呢 感谢

1. 对比[W2725730722](https://github.com/W2725730722/Lenovo-R7000P-2020-Hackintosh)的Ventura EFI，杂七杂八的修改和精简挺多的，难以详细列出。但刚才看了下，受系统版本影响的应该只有这个无线驱动`AirportItlwm-Sonoma.kext`，你可以在[OpenIntelWireless/itlwm](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.3.0-alpha)找到其他系统适用的版本。本仓库的其他修改应当适用于所有系统版本。
![image](https://github.com/jimlee2048/Hackintosh-Lenovo-Legion-R7000P2020H/assets/21117946/90c81797-5f41-4795-bbdd-421f5b50d295)
2. 如上条回复所属，个人仍然建议在备份好数据后，格掉原有EFI&系统，然后在本仓库EFI的基础上进行全新安装，这样能最大程度避免问题。
3. 如果你仍希望在现有Ventura EFI基础上直接升EFI，你可以尝试：（⚠️ 以下流程仅供参考，没有实际尝试过，风险自负）
    - 备份好当前的EFI
    - 升级OpenCore引导和各驱动kext版本
    - 自行准备适合你系统版本的`AirportItlwm.kext`。你可以同时导入多个适配不同系统版本`AirportItlwm.kext`，然后通过设置MinKernel和MaxKernal的系统版本号限制，以保证不同的专版驱动只在检测到合适的系统才工作。
    - 注意，使用存在Sonoma专版支持的新版AirportItlwm v2.3.0的同时，你还需要确保`IntelBTPatcher.kext`和`IntelBluetoothFirmware.kext`同步更新到v2.3.0
    - 暂时禁用显卡驱动NootReded.kext
    - 保存修改后重启，先RESET NVRAM一下，然后进现有Ventura。确认修改后的EFI还能在Ventura下正常工作。
    - 通过系统设置触发升级Sonoma
    - 如果能正常走完升级流程且能最终成功进入到Sonoma的桌面，重新启用显卡驱动NootReded.kext，然后重启
4. Windows下获取macos安装镜像的一个方法：https://sumingyd.github.io/OpenCore-Install-Guide/installer-guide/windows-install.html
