### ISSUE TITLE
无法进入macOS安装界面

### ISSUE THREAD

**Issue by KingStarPlus** [jimlee2048/Hackintosh-Lenovo-Legion-R7000P2020H#5]
我按照步骤操作以后在oc界面选择install mac os以后风扇猛转然后就自己关机了

**Comment by jimlee2048** [comment]
安装前禁掉核显驱动`NootedRed.kext`了吗？
![CleanShot 2024-04-26 at 09 03 04@2x](https://github.com/jimlee2048/Hackintosh-Lenovo-Legion-R7000P2020H/assets/21117946/2bd10afe-aa5d-4c02-8504-900bd04c9dfc)
